pub enum LexerTokens {
    Identifier(String),
    Number(String),
    Float(String),
    Plus,
    Minus,
    Multiply,
    Divide,
    Modulo,
    Equals,
    NotEquals,
    GreaterThan,
    LessThan,
    GreaterThanEquals,
    LessThanEquals,
    And,
    Or,
    Not,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Semicolon,
    Colon,
    Comma,
    Dot,
    String(String),
    Boolean(bool),
    SOI,
    EOF,

    // Keywords are tokens like import, export, for, etc.
    Keyword(String),
}
