name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust llvm
      run: rustup toolchain install nightly --component llvm-tools-preview
    - name: Install LLVM and Clang
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: 18
    - name: Clippy
      run: cargo clippy
    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov --locked
    - name: test with coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        fail_ci_if_error: true
